name: events
run-name: Events

on:
  - push
  - pull_request

jobs:
  show-ref-and-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Echo SHA and REF
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
