name: shell-and-workdirs
run-name: Shells e Diretorios de Trabalho

on:
  - push

jobs:
  display-wordir-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display workdir and list files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
